account/urls.py
from django.conf.urls import url
from . import views

app_name = 'account'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

articles/urls.py
from django.conf.urls import url
from . import views
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'articles'

urlpatterns = [
    url(r'^$',views.article_list, name="list"),
    url(r'^create/$', views.article_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
]

# urlpatterns += staticfiles_urlpatterns

djangonautic/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^account/', include('account.urls')),
    url(r'^about/$',views.about_page),
    url(r'^$', article_views.article_list, name='home'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User



class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None,on_delete=models.CASCADE)
    
    # author
    def __str__(self):
        return self.title
    def snippet(self):
        return self.body[:50] + '...'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb']

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            #log the user in
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'account/signup.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #log in the user
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'account/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms


# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html', {'articles': articles})


def article_detail(request,slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})


@login_required(login_url="/account/login")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            #save article to db
            instances = form.save(commit = False)
            instances.author = request.user
            instances.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form':form})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def about_page(request):
    # return HttpResponse('About Page is created')
    return render(request, 'about_page.html')


def home_page(request):
    # return HttpResponse('Home Page is created')
    return render(request, 'home_page.html')

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an Awesome a new article</h2>
        <form class='site-form' action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Article Infromation</h1>
    <div class="article-detail">
      <div class="article" style="display:flex; flex-direction:column; align-items:center;justify-content:center">
        <h2>{{ article.title }}</h2>
        <p style='color:white'>{{ article.body }}</p>
        <p style='color:white'>{{ article.date }}</p>
        <img src="{{ article.thumb.url }}" alt="picture">
      </div>
    </div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Article List</h1>
    <div class="cards">
      {% for article in articles %}
        <div class="card">
          <div class="container">
            <a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a>
            <h3>{{ article.snippet }}</h3>
            <h5>{{ article.date }}</h5>
            <p class="author">added by {{article.author.username}}</p>
          </div>
        </div>
      {% endfor %}
    </div>
{% endblock %}

templates/about_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About page</title>
  </head>
  <body>
    <h1>About page is HBBH</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </body>
</html>

templates/base_layout.html
{% load static from static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
  </head>
  <body>
    <div class="wrapper">
      <nav>
        <h1><a href="{% url 'home' %}" ><img width='100px' height='100px' src='{% static 'about_me_pic2.jpg' %}'/></a></h1>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <form class="logout-link" action="{% url 'account:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit">
                Log Out
              </button>
            </form>
          </li>
          <li>
            <a href="{% url 'articles:create' %}" class="highlight">
              New article
            </a>
          </li>
          {% else %}
          <li>
            <form class="login-link" action="{% url 'account:login' %}" method="post">
              {% csrf_token %}
              <button type="submit">
                Log In
              </button>
            </form>
          </li>
          <li>
            <form class="signup-link" action="{% url 'account:signup' %}"" method="post">
              {% csrf_token %}
              <button type="submit">
                Signup
              </button>
            </form>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% block content %}
  
      {% endblock %}
    </div>
  </body>
</html>

templates/home_page.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home page</title>
  </head>
  <body>
    <h1>Home page is HBBH</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </body>
</html>